name: Daily Email Reminder

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 06:00 UTC = 08:00 Germany time

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt || echo "no requirements"
      - name: Run reminder script
        run: python learn_reminder.py
        env:
          EMAIL: ${{ secrets.EMAIL }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
